#!/usr/bin/env bash

COMPILE_IGNORE='ios/**,node_modules/**,playground/web/playground.es6,__tests__/**,**/__tests__/**,playground/ios/**'

./node_modules/.bin/babel $1 --ignore $COMPILE_IGNORE --extensions .es6 --out-dir . .
