#!/usr/bin/env bash

IOS=./playground/ios
WEB=./playground/web

# ./node_modules/.bin/watchify --no-bundle-external --extension .es6 -o $IOS/playground.js -v -d $IOS/playground.es6 &
./node_modules/.bin/watchify --no-bundle-external --extension .es6 -o $WEB/playground.js -v -d $WEB/playground.es6 &
./node_modules/.bin/watchify `.bin/extract-dependencies` \
  -r react/addons \
  -r flummox/component \
  -r panels-app \
  -r panels-app/panels/container \
  -r panels-ui/blocks -v -o $WEB/vendor.js ./package.json &
./node_modules/.bin/livereloadify $WEB &
sudo .bin/server.es6
# ./node_modules/.bin/static $WEB --port 3000 --cache 0
